### PR TITLE
Fix: Preserve whitespace in default param string values (fixes #157)

### LINKED ISSUE #157: default param value of " " is trimmed to an empty string ""
In the [doctrine demo](http://eslint.org/doctrine/demo/) try:
```
     * @param {string} [chars='     '] Foo.
```
Then in the dev console of the demo:
```js
var result = doctrine.parse($('#code').val(), { sloppy: true, unwrap: true });
```
You'll see the `result.tags[0]['default']` is `"''"` instead of `"'   '"`.

### PR DESCRIPTION
**Pull request by kaicataldo**

### CODE REVIEW

File: lib/doctrine.js [hunk 1]
```diff
@@ -351,13 +351,46 @@
...
+                                ch = source.charCodeAt(index);
+                            }
+                        }
+
+                        if (ch === 0x27 /* ''' */) {
+                            if (!insideString) {
+                                insideString = '\'';
+                            } else {
+                                if (insideString === '\'') {
+                                    insideString = false;
```
Comment (nzakas) [inline lib/doctrine.js]: Maybe use empty string to keep the data type the same?

File: lib/doctrine.js [hunk 2]
```diff
@@ -351,13 +351,46 @@
...
+                            if (!insideString) {
+                                insideString = '"';
+                            } else {
+                                if (insideString === '"') {
+                                    insideString = false;
+                                }
+                            }
+                        }
+
+                        if (ch === 0x60 /* '`' */) {
```
Comment (nzakas) [inline lib/doctrine.js]: Is this needed?

Comment (kaicataldo) [inline lib/doctrine.js]: I wasn't sure, so I included it - can definitely remove if you don't think it is

File: lib/doctrine.js (hunk 1 above)
Comment (kaicataldo) [inline lib/doctrine.js]: Makes sense :+1:

File: lib/doctrine.js (hunk 2 above)
Comment (nzakas) [inline lib/doctrine.js]: I don't think JSDoc support backticks in default param value position. Can you double check?

Comment (kaicataldo) [inline lib/doctrine.js]: Will do - I'll try to get around to updating tonight. Thanks!

Comment (kaicataldo) [inline lib/doctrine.js]: I haven't found anything about backticks (though nothing in the JSDoc docs seems to say anything about single or double quotes either). In fact, the example they give for a param with a default value that's a string is:

```js
/**
 * @param {string} [somebody=John Doe] - Somebody's name.
 */
function sayHello(somebody) {
    if (!somebody) {
        somebody = 'John Doe';
    }
    alert('Hello ' + somebody);
}
```

I'll remove the backticks. I like working on these JSDoc issues because I'm not super familiar beyond the basics and I learn a lot every time I dig in 😄

**Comment by kaicataldo** [comment]
Updated

**Comment by nzakas** [comment]
Lgtm
